---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-films
  labels:
    app: ingestion-films
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-films
  template:
    metadata:
      labels:
        app: ingestion-films
    spec:
      containers:
      - name: ingestion-films
        image: registry.paranoids.us/ingestion-films:main
        imagePullPolicy: Always
        env:
          - name: IFS_HOST
            value: 0.0.0.0
          - name: IFS_PORT
            value: "4000"
          - name: IFS_SERVICE_NAME
            value: ingestion-films
          - name: IFS_DEBUG
            value: "False"
          - name: IFS_DATABASE_HOST
            value: pgsql-svc.databases.svc
          - name: IFS_DATABASE_NAME
            value: ingestion_films
          - name: IFS_TMDB_URL
            value: https://api.themoviedb.org/
          - name: IFS_PLEX_API_URL
            value: http://192.168.105.105:32400/
          - name: IFS_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: ingestion-films-secrets
                key: username
          - name: IFS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingestion-films-secrets
                key: password
          - name: IFS_TMDB_API_KEY
            valueFrom:
              secretKeyRef:
                name: ingestion-films-secrets
                key: apiKey

        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-films-svc
spec:
  selector:
    app: ingestion-films
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000